import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/Navigation";
import Footer from "./components/Footer";
import NewsStrip from "./components/NewsStrip";
import Image from "next/image";
import { getAds } from "./actions";

const cairo = Cairo({
	variable: "--font-cairo",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Al Dar News",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const ads = await getAds();

	return (
		<html lang="ar" dir="rtl">
			<body className={`${cairo.variable} antialiased`}>
				<Navigation banners={ads} />
				<NewsStrip />
				<main className="flex">
					<div className="hidden md:flex md:flex-1/5 ">
						<div className=" sticky top-8 mt-4 me-8 ms-auto h-[600px]  w-[160px]">
							<Image
								src="/ads/ad_160x600.jpg"
								alt="ad 1"
								width={160}
								height={600}
							/>
						</div>
					</div>
					<div className="flex-1/5 md:flex-3/5">{children}</div>
					<div className="hidden md:flex md:flex-1/5 ">
						<div className=" sticky top-8  mt-4  ms-8 me-auto h-[600px]  w-[160px]">
							<Image
								src="/ads/ad_160x600.jpg"
								alt="ad 1"
								width={160}
								height={600}
							/>
						</div>
					</div>
				</main>
				<Footer />
			</body>
		</html>
	);
}
